### ISSUE TITLE
Align Redeems page with Deposits page

### ISSUE THREAD

**Issue by pdyraga** [suntzu93/tbtcv2_website_info#1]
I would consider two updates to the Redeems page to align it with the Deposits page.

1. Display "Amount requested" and "Amount received"

    Just like for deposits, the Bridge has a redemption fee that may be non-zero. Given this information is displayed for deposits, I think we should have the same columns for redemptions.

2. Remove "Completed TxHash" column

    To leave enough space for "Amount received", I would move the transaction link to the redemption details that can be unfolded by clicking at the given redemption request. This would work the same way as the BTC deposit transaction (Funding TXHash).

**Comment by suntzu93** [comment]
Thank you for your suggestion. I have updated website, if you have any other suggestions let me know.

**Comment by pdyraga** [comment]
I looked at the website and it looks great. The only change I'd implement to is rename "Amount received" to "Amount to receive". Alternatively, do not display the value until the redemption is completed.

Right now, we have kind of a weird state when the redemption was just requested and we say the redeemer already received some amount:
![image](https://github.com/suntzu93/tbtcv2_website_info/assets/4712360/34c4e8c0-b987-4632-9091-1e4b11bc9868)

For what is worth, the same is with Deposits and "Amount received".

**Comment by pdyraga** [comment]
Actually, for deposits it looks differently. Until tBTC is minted, the amount received is zero:

![image](https://github.com/suntzu93/tbtcv2_website_info/assets/4712360/5771e386-fdee-4fc2-88dd-ce8c1c54d4ed)

This is this option but with 0 instead of empty:

> Alternatively, do not display the value until the redemption is completed.

I think this is valid as well.
